# Generated by Django 4.1.1 on 2022-10-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='produtos/'),
        ),
    ]
