# Generated by Django 4.1.1 on 2022-10-19 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
    ]
