# Generated by Django 4.1.1 on 2022-10-19 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_produto_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='imagen',
            new_name='imagem',
        ),
    ]
